sudo: false
language: node_js

## Set nodejs version
node_js:
  - 6
  - 8
  - stable
## Set mysql & redis
services:
  - mysql
  - redis-server

before_install:
  ## Create datebase
  - mysql -e 'CREATE DATABASE IF NOT EXISTS botphus_test;'
  ## Change password
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('123456') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade -u root -pnew_password
  - sudo service mysql restart

script: npm run test

after_success:
  - bash <(curl -s https://codecov.io/bash)